language: java
sudo: required
install: true

services:
  - docker

jdk:
  - oraclejdk8

env:
  - sonarqube: 5.6.7
  - sonarqube: 6.3.1
  - sonarqube: 6.6
  - sonarqube: 6.7
  - sonarqube: 6.7.1
  - sonarqube: 6.7.2
  - sonarqube: 6.7.3
  - sonarqube: 6.7.4
  - sonarqube: 6.7.5
  - sonarqube: 7.0
  - sonarqube: 7.1
  - sonarqube: 7.2
  - sonarqube: 7.2.1
  - sonarqube: 7.3

before_install:
  - docker run -d -p 127.0.0.1:9000:9000/tcp sonarqube:${sonarqube}-alpine
  - echo "Waiting 5 minutes for SonarQube..."
  - sleep 300

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  - src/test/it/run-test.sh
  
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: false
